### ISSUE TITLE
Crystal aura

### ISSUE THREAD

**Issue by master7720** [Sxmurai/inferno#46]
Idk if it was my config but the ca was not working

**Comment by HausemasterIssue** [comment]
the autocrystal is still in very early development. it was only added a few days ago, it will improve and overtime become very powerful. it's not a config issue, the autocrystal right now is just really bad. don't use it, but overtime it will be good. use something like gamesense for the time being :)

**Comment by master7720** [comment]
ah ok

**Comment by Sxmurai** [comment]
the autocrystal does work, its just very, very, very chinese. it places and breaks and ive taken it on 2b2bpvp.net to test it out and ive killed a few people. however the rotations dont work as theyre supposed to and i need to look into that. since its the weekend after today, i'll get to fixing it and hopefully making it a really good AC for stricter NCP servers.
